### ISSUE TITLE
No scrollbar when inspecting large set of unique values in Value distribution analysis

### ISSUE THREAD

**Issue by arjansh** [datacleaner/DataCleaner#1073]
When inspecting a large set of unique values in the results of a Value distribution analysis the panel itself is not resized, as a result of which no scrollbar appears and you cannot scroll through the results. When you resize the window a scrollbar appears. Vice versa, when you go back from the large set of unique values to the value distribution overview, the scrollbar doesn't disappear until you either resize the window or try to use the scrollbar.

_Steps to reproduce_
- Create a new job from scratch and use the Customers datastore.
- Add a Value distribution analyzer and select the id field as input column.
- Execute the job.
- Now click the green arrow in the table to view all unique value counts.

Notice that the table is bigger than the window and there is no scrollbar (not even a tiny one). If you resize the window, a scrollbar appears.

**Comment by arjansh** [comment]
![2016-01-19 14_07_53-customers _ analysis results _ datacleaner](https://cloud.githubusercontent.com/assets/16542747/12419402/29b2eb86-beb6-11e5-8a7a-449c10ac5a44.png)

**Comment by ClaudiaPHI** [comment]
This is similar with https://github.com/datacleaner/DataCleaner/issues/1040.

**Comment by kaspersorensen** [comment]
But I guess #1040 is fixed now ... So @arjansh can you please confirm that this is still the case on master branch?

**Comment by arjansh** [comment]
@kaspersorensen I just re-tested this on an updated master branch, but this is not fixed by #1040. The problem here is not that the scrollbar thumb is too small, it is not there at all. It seems like the panel's size isn't recalculated when a larger (or smaller) table is loaded into it. If you resize the window, the panel's size is recalculated and the scrollbar appears.

**Comment by kaspersorensen** [comment]
OK good to have that clarification, thanks.
